
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: preserve
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: off
